S1-05: Skapa initial cucumberkonfiguration
Moraxan/agiletest pull request #2
Opened 2024-11-14 14:08 UTC by baraabd

2024-11-14 17:27 UTC, Moraxan commented
Springboot finns inte längre i pom.xml, är det avsiktligt?

2024-11-14 18:45 UTC, Moraxan requested changes
The pom.xml is missing dependencies from initial project. 
Sprinboot mainly.

2024-11-14 19:40 UTC, baraabd commented
Ja, Jag har tagit bort Sprintboot eftersom det behövs inte under testing, tror jag.

2024-11-15 06:35 UTC, Moraxan commented
Nu ser jag att hela API:et är borta från den här pullrequesten

![image](https://github.com/user-attachments/assets/ab5b01cb-faa9-4976-af38-ad9bb897a9fd)

2024-11-15 07:58 UTC, baraabd commented
Jag har en tanke för detta tillfället att ta bort API strukturen för att fokusera på att implementera tester steg för steg. På detta sätt kan vi förstå processen och lära oss hur vi bäst genomför testerna. Vi kommer att lägga till API strukturen senare när vi är redo att implementera API tester.

Vi kommer lägga till PPI "Initial API strukturen för test" på projekt senare. 

Hoppas att jag har övertygat dig! annars jag kommer lämna dem tilbaka.

2024-11-15 08:03 UTC, Moraxan commented
Jag är inte övertygad. Vi måste ju skriva testerna på det projekt vi ska testa. Att vi gör om kursens delsteg 1 är tidsödande och kontraproduktivt. Tiden kommer vara knapp som den är. Det är mindre än en månad kvar till examensdagen. 

Om vi ser det som en bra idé i gruppen, så kan vi lägga upp ett sidoprojekt för att göra om delsteg 1 av kursen. I övrigt bör API-projektet behålla den struktur det haft från början.

2024-11-15 08:17 UTC, baraabd commented
> Jag är inte övertygad. Vi måste ju skriva testerna på det projekt vi ska testa. Att vi gör om kursens delsteg 1 är tidsödande och kontraproduktivt. Tiden kommer vara knapp som den är. Det är mindre än en månad kvar till examensdagen.
> 
> Om vi ser det som en bra idé i gruppen, så kan vi lägga upp ett sidoprojekt för att göra om delsteg 1 av kursen. I övrigt bör API-projektet behålla den struktur det haft från början.

2024-11-15 08:17 UTC, closed without merging